/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as IconsRouteImport } from './routes/icons'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as PicksRouteImport } from './routes/picks'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ScreenRouteImport } from './routes/screen'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as ApiCloseRouteImport } from './routes/api/close'
import { Route as ApiEnrichRouteImport } from './routes/api/enrich'
import { Route as ApiFundamentalsRouteImport } from './routes/api/fundamentals'
import { Route as ApiHistoriesRouteImport } from './routes/api/histories'
import { Route as ApiHistoryRouteImport } from './routes/api/history'
import { Route as ApiMacroRouteImport } from './routes/api/macro'
import { Route as ApiNewsRouteImport } from './routes/api/news'
import { Route as ApiNoteRouteImport } from './routes/api/note'
import { Route as ApiOhlcRouteImport } from './routes/api/ohlc'
import { Route as ApiQuoteRouteImport } from './routes/api/quote'
import { Route as ApiScreenBuildRouteImport } from './routes/api/screen-build'
import { Route as ApiScreenerRouteImport } from './routes/api/screener'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiSeasonalityRouteImport } from './routes/api/seasonality'
import { Route as ApiSkillBoardRouteImport } from './routes/api/skill-board'
import { Route as ApiTapeRouteImport } from './routes/api/tape'
import { Route as ApiWikiRouteImport } from './routes/api/wiki'
import { Route as PIdRouteImport } from './routes/p.$id'
import { Route as SSymbolRouteImport } from './routes/s.$symbol'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PIdIndexRouteImport } from './routes/p.$id.index'
import { Route as PIdHoldingsRouteImport } from './routes/p.$id.holdings'
import { Route as PIdImproveRouteImport } from './routes/p.$id.improve'
import { Route as PIdPathRouteImport } from './routes/p.$id.path'
import { Route as PIdPerformanceRouteImport } from './routes/p.$id.performance'
import { Route as PIdRiskRouteImport } from './routes/p.$id.risk'
import { Route as PIdSeasonalityRouteImport } from './routes/p.$id.seasonality'
import { Route as PIdSectorsRouteImport } from './routes/p.$id.sectors'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const IconsRoute = IconsRouteImport.update({
  id: '/icons',
  path: '/icons',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const PicksRoute = PicksRouteImport.update({
  id: '/picks',
  path: '/picks',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenRoute = ScreenRouteImport.update({
  id: '/screen',
  path: '/screen',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCloseRoute = ApiCloseRouteImport.update({
  id: '/api/close',
  path: '/api/close',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEnrichRoute = ApiEnrichRouteImport.update({
  id: '/api/enrich',
  path: '/api/enrich',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFundamentalsRoute = ApiFundamentalsRouteImport.update({
  id: '/api/fundamentals',
  path: '/api/fundamentals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoriesRoute = ApiHistoriesRouteImport.update({
  id: '/api/histories',
  path: '/api/histories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMacroRoute = ApiMacroRouteImport.update({
  id: '/api/macro',
  path: '/api/macro',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsRoute = ApiNewsRouteImport.update({
  id: '/api/news',
  path: '/api/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNoteRoute = ApiNoteRouteImport.update({
  id: '/api/note',
  path: '/api/note',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOhlcRoute = ApiOhlcRouteImport.update({
  id: '/api/ohlc',
  path: '/api/ohlc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuoteRoute = ApiQuoteRouteImport.update({
  id: '/api/quote',
  path: '/api/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScreenBuildRoute = ApiScreenBuildRouteImport.update({
  id: '/api/screen-build',
  path: '/api/screen-build',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScreenerRoute = ApiScreenerRouteImport.update({
  id: '/api/screener',
  path: '/api/screener',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeasonalityRoute = ApiSeasonalityRouteImport.update({
  id: '/api/seasonality',
  path: '/api/seasonality',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSkillBoardRoute = ApiSkillBoardRouteImport.update({
  id: '/api/skill-board',
  path: '/api/skill-board',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTapeRoute = ApiTapeRouteImport.update({
  id: '/api/tape',
  path: '/api/tape',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWikiRoute = ApiWikiRouteImport.update({
  id: '/api/wiki',
  path: '/api/wiki',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdRoute = PIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SSymbolRoute = SSymbolRouteImport.update({
  id: '/s/$symbol',
  path: '/s/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdIndexRoute = PIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PIdRoute,
} as any)
const PIdHoldingsRoute = PIdHoldingsRouteImport.update({
  id: '/holdings',
  path: '/holdings',
  getParentRoute: () => PIdRoute,
} as any)
const PIdImproveRoute = PIdImproveRouteImport.update({
  id: '/improve',
  path: '/improve',
  getParentRoute: () => PIdRoute,
} as any)
const PIdPathRoute = PIdPathRouteImport.update({
  id: '/path',
  path: '/path',
  getParentRoute: () => PIdRoute,
} as any)
const PIdPerformanceRoute = PIdPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => PIdRoute,
} as any)
const PIdRiskRoute = PIdRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => PIdRoute,
} as any)
const PIdSeasonalityRoute = PIdSeasonalityRouteImport.update({
  id: '/seasonality',
  path: '/seasonality',
  getParentRoute: () => PIdRoute,
} as any)
const PIdSectorsRoute = PIdSectorsRouteImport.update({
  id: '/sectors',
  path: '/sectors',
  getParentRoute: () => PIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/compare': typeof CompareRoute
  '/icons': typeof IconsRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/picks': typeof PicksRoute
  '/privacy': typeof PrivacyRoute
  '/screen': typeof ScreenRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/trade': typeof TradeRoute
  '/watch': typeof WatchRoute
  '/api/close': typeof ApiCloseRoute
  '/api/enrich': typeof ApiEnrichRoute
  '/api/fundamentals': typeof ApiFundamentalsRoute
  '/api/histories': typeof ApiHistoriesRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/macro': typeof ApiMacroRoute
  '/api/news': typeof ApiNewsRoute
  '/api/note': typeof ApiNoteRoute
  '/api/ohlc': typeof ApiOhlcRoute
  '/api/quote': typeof ApiQuoteRoute
  '/api/screen-build': typeof ApiScreenBuildRoute
  '/api/screener': typeof ApiScreenerRoute
  '/api/search': typeof ApiSearchRoute
  '/api/seasonality': typeof ApiSeasonalityRoute
  '/api/skill-board': typeof ApiSkillBoardRoute
  '/api/tape': typeof ApiTapeRoute
  '/api/wiki': typeof ApiWikiRoute
  '/p/$id': typeof PIdRouteWithChildren
  '/s/$symbol': typeof SSymbolRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/p/$id/holdings': typeof PIdHoldingsRoute
  '/p/$id/improve': typeof PIdImproveRoute
  '/p/$id/path': typeof PIdPathRoute
  '/p/$id/performance': typeof PIdPerformanceRoute
  '/p/$id/risk': typeof PIdRiskRoute
  '/p/$id/seasonality': typeof PIdSeasonalityRoute
  '/p/$id/sectors': typeof PIdSectorsRoute
  '/p/$id/': typeof PIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/compare': typeof CompareRoute
  '/icons': typeof IconsRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/picks': typeof PicksRoute
  '/privacy': typeof PrivacyRoute
  '/screen': typeof ScreenRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/trade': typeof TradeRoute
  '/watch': typeof WatchRoute
  '/api/close': typeof ApiCloseRoute
  '/api/enrich': typeof ApiEnrichRoute
  '/api/fundamentals': typeof ApiFundamentalsRoute
  '/api/histories': typeof ApiHistoriesRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/macro': typeof ApiMacroRoute
  '/api/news': typeof ApiNewsRoute
  '/api/note': typeof ApiNoteRoute
  '/api/ohlc': typeof ApiOhlcRoute
  '/api/quote': typeof ApiQuoteRoute
  '/api/screen-build': typeof ApiScreenBuildRoute
  '/api/screener': typeof ApiScreenerRoute
  '/api/search': typeof ApiSearchRoute
  '/api/seasonality': typeof ApiSeasonalityRoute
  '/api/skill-board': typeof ApiSkillBoardRoute
  '/api/tape': typeof ApiTapeRoute
  '/api/wiki': typeof ApiWikiRoute
  '/s/$symbol': typeof SSymbolRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/p/$id/holdings': typeof PIdHoldingsRoute
  '/p/$id/improve': typeof PIdImproveRoute
  '/p/$id/path': typeof PIdPathRoute
  '/p/$id/performance': typeof PIdPerformanceRoute
  '/p/$id/risk': typeof PIdRiskRoute
  '/p/$id/seasonality': typeof PIdSeasonalityRoute
  '/p/$id/sectors': typeof PIdSectorsRoute
  '/p/$id': typeof PIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/compare': typeof CompareRoute
  '/icons': typeof IconsRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/picks': typeof PicksRoute
  '/privacy': typeof PrivacyRoute
  '/screen': typeof ScreenRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/trade': typeof TradeRoute
  '/watch': typeof WatchRoute
  '/api/close': typeof ApiCloseRoute
  '/api/enrich': typeof ApiEnrichRoute
  '/api/fundamentals': typeof ApiFundamentalsRoute
  '/api/histories': typeof ApiHistoriesRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/macro': typeof ApiMacroRoute
  '/api/news': typeof ApiNewsRoute
  '/api/note': typeof ApiNoteRoute
  '/api/ohlc': typeof ApiOhlcRoute
  '/api/quote': typeof ApiQuoteRoute
  '/api/screen-build': typeof ApiScreenBuildRoute
  '/api/screener': typeof ApiScreenerRoute
  '/api/search': typeof ApiSearchRoute
  '/api/seasonality': typeof ApiSeasonalityRoute
  '/api/skill-board': typeof ApiSkillBoardRoute
  '/api/tape': typeof ApiTapeRoute
  '/api/wiki': typeof ApiWikiRoute
  '/p/$id': typeof PIdRouteWithChildren
  '/s/$symbol': typeof SSymbolRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/p/$id/holdings': typeof PIdHoldingsRoute
  '/p/$id/improve': typeof PIdImproveRoute
  '/p/$id/path': typeof PIdPathRoute
  '/p/$id/performance': typeof PIdPerformanceRoute
  '/p/$id/risk': typeof PIdRiskRoute
  '/p/$id/seasonality': typeof PIdSeasonalityRoute
  '/p/$id/sectors': typeof PIdSectorsRoute
  '/p/$id/': typeof PIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/compare'
    | '/icons'
    | '/login'
    | '/markets'
    | '/picks'
    | '/privacy'
    | '/screen'
    | '/signup'
    | '/terms'
    | '/trade'
    | '/watch'
    | '/api/close'
    | '/api/enrich'
    | '/api/fundamentals'
    | '/api/histories'
    | '/api/history'
    | '/api/macro'
    | '/api/news'
    | '/api/note'
    | '/api/ohlc'
    | '/api/quote'
    | '/api/screen-build'
    | '/api/screener'
    | '/api/search'
    | '/api/seasonality'
    | '/api/skill-board'
    | '/api/tape'
    | '/api/wiki'
    | '/p/$id'
    | '/s/$symbol'
    | '/api/auth/$'
    | '/p/$id/holdings'
    | '/p/$id/improve'
    | '/p/$id/path'
    | '/p/$id/performance'
    | '/p/$id/risk'
    | '/p/$id/seasonality'
    | '/p/$id/sectors'
    | '/p/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/compare'
    | '/icons'
    | '/login'
    | '/markets'
    | '/picks'
    | '/privacy'
    | '/screen'
    | '/signup'
    | '/terms'
    | '/trade'
    | '/watch'
    | '/api/close'
    | '/api/enrich'
    | '/api/fundamentals'
    | '/api/histories'
    | '/api/history'
    | '/api/macro'
    | '/api/news'
    | '/api/note'
    | '/api/ohlc'
    | '/api/quote'
    | '/api/screen-build'
    | '/api/screener'
    | '/api/search'
    | '/api/seasonality'
    | '/api/skill-board'
    | '/api/tape'
    | '/api/wiki'
    | '/s/$symbol'
    | '/api/auth/$'
    | '/p/$id/holdings'
    | '/p/$id/improve'
    | '/p/$id/path'
    | '/p/$id/performance'
    | '/p/$id/risk'
    | '/p/$id/seasonality'
    | '/p/$id/sectors'
    | '/p/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/compare'
    | '/icons'
    | '/login'
    | '/markets'
    | '/picks'
    | '/privacy'
    | '/screen'
    | '/signup'
    | '/terms'
    | '/trade'
    | '/watch'
    | '/api/close'
    | '/api/enrich'
    | '/api/fundamentals'
    | '/api/histories'
    | '/api/history'
    | '/api/macro'
    | '/api/news'
    | '/api/note'
    | '/api/ohlc'
    | '/api/quote'
    | '/api/screen-build'
    | '/api/screener'
    | '/api/search'
    | '/api/seasonality'
    | '/api/skill-board'
    | '/api/tape'
    | '/api/wiki'
    | '/p/$id'
    | '/s/$symbol'
    | '/api/auth/$'
    | '/p/$id/holdings'
    | '/p/$id/improve'
    | '/p/$id/path'
    | '/p/$id/performance'
    | '/p/$id/risk'
    | '/p/$id/seasonality'
    | '/p/$id/sectors'
    | '/p/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  CompareRoute: typeof CompareRoute
  IconsRoute: typeof IconsRoute
  LoginRoute: typeof LoginRoute
  MarketsRoute: typeof MarketsRoute
  PicksRoute: typeof PicksRoute
  PrivacyRoute: typeof PrivacyRoute
  ScreenRoute: typeof ScreenRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  TradeRoute: typeof TradeRoute
  WatchRoute: typeof WatchRoute
  ApiCloseRoute: typeof ApiCloseRoute
  ApiEnrichRoute: typeof ApiEnrichRoute
  ApiFundamentalsRoute: typeof ApiFundamentalsRoute
  ApiHistoriesRoute: typeof ApiHistoriesRoute
  ApiHistoryRoute: typeof ApiHistoryRoute
  ApiMacroRoute: typeof ApiMacroRoute
  ApiNewsRoute: typeof ApiNewsRoute
  ApiNoteRoute: typeof ApiNoteRoute
  ApiOhlcRoute: typeof ApiOhlcRoute
  ApiQuoteRoute: typeof ApiQuoteRoute
  ApiScreenBuildRoute: typeof ApiScreenBuildRoute
  ApiScreenerRoute: typeof ApiScreenerRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiSeasonalityRoute: typeof ApiSeasonalityRoute
  ApiSkillBoardRoute: typeof ApiSkillBoardRoute
  ApiTapeRoute: typeof ApiTapeRoute
  ApiWikiRoute: typeof ApiWikiRoute
  PIdRoute: typeof PIdRouteWithChildren
  SSymbolRoute: typeof SSymbolRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/icons': {
      id: '/icons'
      path: '/icons'
      fullPath: '/icons'
      preLoaderRoute: typeof IconsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/picks': {
      id: '/picks'
      path: '/picks'
      fullPath: '/picks'
      preLoaderRoute: typeof PicksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screen': {
      id: '/screen'
      path: '/screen'
      fullPath: '/screen'
      preLoaderRoute: typeof ScreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/close': {
      id: '/api/close'
      path: '/api/close'
      fullPath: '/api/close'
      preLoaderRoute: typeof ApiCloseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/enrich': {
      id: '/api/enrich'
      path: '/api/enrich'
      fullPath: '/api/enrich'
      preLoaderRoute: typeof ApiEnrichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fundamentals': {
      id: '/api/fundamentals'
      path: '/api/fundamentals'
      fullPath: '/api/fundamentals'
      preLoaderRoute: typeof ApiFundamentalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/histories': {
      id: '/api/histories'
      path: '/api/histories'
      fullPath: '/api/histories'
      preLoaderRoute: typeof ApiHistoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/macro': {
      id: '/api/macro'
      path: '/api/macro'
      fullPath: '/api/macro'
      preLoaderRoute: typeof ApiMacroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news': {
      id: '/api/news'
      path: '/api/news'
      fullPath: '/api/news'
      preLoaderRoute: typeof ApiNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/note': {
      id: '/api/note'
      path: '/api/note'
      fullPath: '/api/note'
      preLoaderRoute: typeof ApiNoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ohlc': {
      id: '/api/ohlc'
      path: '/api/ohlc'
      fullPath: '/api/ohlc'
      preLoaderRoute: typeof ApiOhlcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quote': {
      id: '/api/quote'
      path: '/api/quote'
      fullPath: '/api/quote'
      preLoaderRoute: typeof ApiQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/screen-build': {
      id: '/api/screen-build'
      path: '/api/screen-build'
      fullPath: '/api/screen-build'
      preLoaderRoute: typeof ApiScreenBuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/screener': {
      id: '/api/screener'
      path: '/api/screener'
      fullPath: '/api/screener'
      preLoaderRoute: typeof ApiScreenerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seasonality': {
      id: '/api/seasonality'
      path: '/api/seasonality'
      fullPath: '/api/seasonality'
      preLoaderRoute: typeof ApiSeasonalityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/skill-board': {
      id: '/api/skill-board'
      path: '/api/skill-board'
      fullPath: '/api/skill-board'
      preLoaderRoute: typeof ApiSkillBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tape': {
      id: '/api/tape'
      path: '/api/tape'
      fullPath: '/api/tape'
      preLoaderRoute: typeof ApiTapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wiki': {
      id: '/api/wiki'
      path: '/api/wiki'
      fullPath: '/api/wiki'
      preLoaderRoute: typeof ApiWikiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id': {
      id: '/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof PIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$symbol': {
      id: '/s/$symbol'
      path: '/s/$symbol'
      fullPath: '/s/$symbol'
      preLoaderRoute: typeof SSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id/': {
      id: '/p/$id/'
      path: '/'
      fullPath: '/p/$id/'
      preLoaderRoute: typeof PIdIndexRouteImport
      parentRoute: typeof PIdRoute
    }
    '/p/$id/holdings': {
      id: '/p/$id/holdings'
      path: '/holdings'
      fullPath: '/p/$id/holdings'
      preLoaderRoute: typeof PIdHoldingsRouteImport
      parentRoute: typeof PIdRoute
    }
    '/p/$id/improve': {
      id: '/p/$id/improve'
      path: '/improve'
      fullPath: '/p/$id/improve'
      preLoaderRoute: typeof PIdImproveRouteImport
      parentRoute: typeof PIdRoute
    }
    '/p/$id/path': {
      id: '/p/$id/path'
      path: '/path'
      fullPath: '/p/$id/path'
      preLoaderRoute: typeof PIdPathRouteImport
      parentRoute: typeof PIdRoute
    }
    '/p/$id/performance': {
      id: '/p/$id/performance'
      path: '/performance'
      fullPath: '/p/$id/performance'
      preLoaderRoute: typeof PIdPerformanceRouteImport
      parentRoute: typeof PIdRoute
    }
    '/p/$id/risk': {
      id: '/p/$id/risk'
      path: '/risk'
      fullPath: '/p/$id/risk'
      preLoaderRoute: typeof PIdRiskRouteImport
      parentRoute: typeof PIdRoute
    }
    '/p/$id/seasonality': {
      id: '/p/$id/seasonality'
      path: '/seasonality'
      fullPath: '/p/$id/seasonality'
      preLoaderRoute: typeof PIdSeasonalityRouteImport
      parentRoute: typeof PIdRoute
    }
    '/p/$id/sectors': {
      id: '/p/$id/sectors'
      path: '/sectors'
      fullPath: '/p/$id/sectors'
      preLoaderRoute: typeof PIdSectorsRouteImport
      parentRoute: typeof PIdRoute
    }
  }
}

interface PIdRouteChildren {
  PIdHoldingsRoute: typeof PIdHoldingsRoute
  PIdImproveRoute: typeof PIdImproveRoute
  PIdPathRoute: typeof PIdPathRoute
  PIdPerformanceRoute: typeof PIdPerformanceRoute
  PIdRiskRoute: typeof PIdRiskRoute
  PIdSeasonalityRoute: typeof PIdSeasonalityRoute
  PIdSectorsRoute: typeof PIdSectorsRoute
  PIdIndexRoute: typeof PIdIndexRoute
}

const PIdRouteChildren: PIdRouteChildren = {
  PIdHoldingsRoute: PIdHoldingsRoute,
  PIdImproveRoute: PIdImproveRoute,
  PIdPathRoute: PIdPathRoute,
  PIdPerformanceRoute: PIdPerformanceRoute,
  PIdRiskRoute: PIdRiskRoute,
  PIdSeasonalityRoute: PIdSeasonalityRoute,
  PIdSectorsRoute: PIdSectorsRoute,
  PIdIndexRoute: PIdIndexRoute,
}

const PIdRouteWithChildren = PIdRoute._addFileChildren(PIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  CompareRoute: CompareRoute,
  IconsRoute: IconsRoute,
  LoginRoute: LoginRoute,
  MarketsRoute: MarketsRoute,
  PicksRoute: PicksRoute,
  PrivacyRoute: PrivacyRoute,
  ScreenRoute: ScreenRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  TradeRoute: TradeRoute,
  WatchRoute: WatchRoute,
  ApiCloseRoute: ApiCloseRoute,
  ApiEnrichRoute: ApiEnrichRoute,
  ApiFundamentalsRoute: ApiFundamentalsRoute,
  ApiHistoriesRoute: ApiHistoriesRoute,
  ApiHistoryRoute: ApiHistoryRoute,
  ApiMacroRoute: ApiMacroRoute,
  ApiNewsRoute: ApiNewsRoute,
  ApiNoteRoute: ApiNoteRoute,
  ApiOhlcRoute: ApiOhlcRoute,
  ApiQuoteRoute: ApiQuoteRoute,
  ApiScreenBuildRoute: ApiScreenBuildRoute,
  ApiScreenerRoute: ApiScreenerRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiSeasonalityRoute: ApiSeasonalityRoute,
  ApiSkillBoardRoute: ApiSkillBoardRoute,
  ApiTapeRoute: ApiTapeRoute,
  ApiWikiRoute: ApiWikiRoute,
  PIdRoute: PIdRouteWithChildren,
  SSymbolRoute: SSymbolRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
